//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class apConfig
    {
        public string IdConfig { get; set; }
        public Nullable<int> ProximoNoFactura { get; set; }
        public Nullable<bool> FacturaBloqueado { get; set; }
        public Nullable<int> ProximoNoCredito { get; set; }
        public Nullable<bool> CreditoBloqueado { get; set; }
        public Nullable<int> ProximoNoDebito { get; set; }
        public Nullable<bool> DebitoBloqueado { get; set; }
        public Nullable<bool> AutoIdProveedor { get; set; }
        public Nullable<int> ProximoIdProveedor { get; set; }
        public Nullable<bool> IdProveedorBloqueado { get; set; }
        public Nullable<bool> UsarCuentasContables { get; set; }
    }
}
