//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arConfig
    {
        public string IdConfig { get; set; }
        public int ProximoNoFactura { get; set; }
        public bool FacturaBloqueado { get; set; }
        public bool FacturasPrintTk { get; set; }
        public int ProximoNoRecibo { get; set; }
        public bool ReciboBloqueado { get; set; }
        public int ProximoNoCredito { get; set; }
        public bool CreditoBloqueado { get; set; }
        public int ProximoNoDebito { get; set; }
        public bool DebitoBloqueado { get; set; }
        public bool AutoIdCliente { get; set; }
        public int ProximoIdCliente { get; set; }
        public bool IdClienteBloqueado { get; set; }
        public bool UsarCuentasContables { get; set; }
        public bool UsarRegimenFiscalHN { get; set; }
    }
}
