//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arDescuento
    {
        public string IdDescuento { get; set; }
        public string Descripcion { get; set; }
        public string IdCuenta { get; set; }
        public decimal Valor { get; set; }
        public bool EsPorcentaje { get; set; }
        public bool PermiteEditar { get; set; }
        public decimal ValorMaximo { get; set; }
        public int Orden { get; set; }
        public Nullable<bool> PreAutorizar { get; set; }
        public Nullable<bool> PosAutorizar { get; set; }
        public Nullable<bool> POS { get; set; }
        public bool lStatus { get; set; }
    
        public virtual glCuenta glCuenta { get; set; }
    }
}
