//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arDebito
    {
        public int NoDebito { get; set; }
        public System.DateTime Fecha { get; set; }
        public string IdCliente { get; set; }
        public string Cliente { get; set; }
        public string IdTipoNotaDebito { get; set; }
        public string IdTerminoCredito { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public decimal Pagos { get; set; }
        public decimal Creditos { get; set; }
        public decimal Saldo { get; set; }
        public string ModuloOrigen { get; set; }
        public string Referencia { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string IdUsuario { get; set; }
        public string cStatus { get; set; }
        public bool Posteado { get; set; }
        public Nullable<int> IdCAI { get; set; }
        public string NoDebitoFiscal { get; set; }
    
        public virtual arNotaDebitoTipo arNotaDebitoTipo { get; set; }
    }
}
