//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arFacturasTax
    {
        public int NuId { get; set; }
        public string NoFactura { get; set; }
        public string IdTax { get; set; }
        public Nullable<decimal> TaxValor { get; set; }
        public Nullable<decimal> MontoBase { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual arFactura arFactura { get; set; }
    }
}
