//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arFacturasDescuento
    {
        public int NuId { get; set; }
        public string NoFactura { get; set; }
        public string IdDescuento { get; set; }
        public decimal MontoBase { get; set; }
        public decimal ValorDescuento { get; set; }
        public bool EsPorcentaje { get; set; }
        public decimal MontoDescuento { get; set; }
        public bool Selectivo { get; set; }
        public Nullable<bool> PreAutorizar { get; set; }
        public Nullable<bool> PosAutorizar { get; set; }
        public string AutorizadoPor { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public int OrdenCalculo { get; set; }
        public string Notas { get; set; }
    
        public virtual arFactura arFactura { get; set; }
    }
}
