//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arFacturasDetalle
    {
        public int NuId { get; set; }
        public string NoFactura { get; set; }
        public Nullable<int> NoLinea { get; set; }
        public string IdDepto { get; set; }
        public string TipoCodigo { get; set; }
        public string IdCodigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ListaDePrecio { get; set; }
        public string IdBin { get; set; }
        public Nullable<decimal> ExistenciaAnterior { get; set; }
        public string IdTax { get; set; }
        public Nullable<decimal> TaxValor { get; set; }
        public Nullable<decimal> ImpuestoUnitario { get; set; }
        public Nullable<decimal> PrecioConImpuesto { get; set; }
        public decimal DesPorcentMax { get; set; }
        public decimal DesMontoMax { get; set; }
        public decimal DesPorcentAplicado { get; set; }
    
        public virtual arFactura arFactura { get; set; }
        public virtual icDepto icDepto { get; set; }
        public virtual SysTax SysTax { get; set; }
    }
}
