//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arFactura()
        {
            this.arFacturasDescuentoes = new HashSet<arFacturasDescuento>();
            this.arFacturasDetalles = new HashSet<arFacturasDetalle>();
            this.arFacturasTaxes = new HashSet<arFacturasTax>();
        }
    
        public string NoFactura { get; set; }
        public string IdCliente { get; set; }
        public string Cliente { get; set; }
        public string IdTerminoCredito { get; set; }
        public string IdAlmacen { get; set; }
        public string IdVendedor { get; set; }
        public int NoTurno { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Descuentos { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public decimal Pagos { get; set; }
        public decimal Creditos { get; set; }
        public decimal Saldo { get; set; }
        public string ModuloOrigen { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string IdUsuario { get; set; }
        public string cStatus { get; set; }
        public bool Posteado { get; set; }
        public Nullable<int> IdCAI { get; set; }
        public string NoFacturaFiscal { get; set; }
        public bool OrdComExenta { get; set; }
        public string NoOrdComExe { get; set; }
        public string NoConRegExo { get; set; }
        public string NoRegSag { get; set; }
        public string NoFacProforma { get; set; }
        public decimal ImporteExonerado { get; set; }
        public decimal ImporteExento { get; set; }
    
        public virtual arCliente arCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDescuento> arFacturasDescuentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDetalle> arFacturasDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasTax> arFacturasTaxes { get; set; }
        public virtual arTerminoCredito arTerminoCredito { get; set; }
        public virtual icAlmacene icAlmacene { get; set; }
        public virtual posTurno posTurno { get; set; }
        public virtual posVendedore posVendedore { get; set; }
    }
}
