//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arMetodoPago
    {
        public string IdMetodoPago { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string IdBanco { get; set; }
        public string IdCuenta { get; set; }
        public int Orden { get; set; }
        public bool POS { get; set; }
        public bool lStatus { get; set; }
    
        public virtual bnBanco bnBanco { get; set; }
        public virtual glCuenta glCuenta { get; set; }
    }
}
