//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arRecibosMetodo
    {
        public int NuId { get; set; }
        public int NoRecibo { get; set; }
        public string IdMetodoPago { get; set; }
        public decimal Monto { get; set; }
        public decimal MontoDevuelto { get; set; }
        public bool Depositado { get; set; }
        public string NoDeposito { get; set; }
        public decimal EfectivoRecibido { get; set; }
        public decimal Cambio { get; set; }
    
        public virtual arRecibo arRecibo { get; set; }
    }
}
