//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arServicio
    {
        public string IdServicio { get; set; }
        public string Descripcion { get; set; }
        public string IdTipoServicio { get; set; }
        public string IdClaseServicio { get; set; }
        public string IdCuenta { get; set; }
        public string CodigoBarra { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public Nullable<bool> Tax { get; set; }
        public string IdTax { get; set; }
        public Nullable<bool> EditarPrecio { get; set; }
        public Nullable<bool> FijarPrecio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> PrecioConImpuesto { get; set; }
        public Nullable<decimal> Utilidad { get; set; }
        public Nullable<decimal> UtilidadPorcent { get; set; }
        public Nullable<decimal> PorcentajeMaxDescuento { get; set; }
        public Nullable<decimal> MontoMaxDescuento { get; set; }
        public string Notas { get; set; }
        public bool Activo { get; set; }
    
        public virtual arServicioClase arServicioClase { get; set; }
        public virtual arServicioTipo arServicioTipo { get; set; }
        public virtual SysTax SysTax { get; set; }
    }
}
