//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bnBanco()
        {
            this.arMetodoPagoes = new HashSet<arMetodoPago>();
        }
    
        public string IdBanco { get; set; }
        public string Descripcion { get; set; }
        public string IdMoneda { get; set; }
        public string ABA { get; set; }
        public string NoCuenta { get; set; }
        public string IdCuenta { get; set; }
        public bool EmiteCk { get; set; }
        public int UltimoCk { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arMetodoPago> arMetodoPagoes { get; set; }
        public virtual bnMoneda bnMoneda { get; set; }
        public virtual glCuenta glCuenta { get; set; }
    }
}
