//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcCodigosDeduccion
    {
        public string IdCodDeduccion { get; set; }
        public string Descripcion { get; set; }
        public string IdCuenta { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<bool> EsPorcent { get; set; }
        public Nullable<bool> lStatus { get; set; }
    }
}
