//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcConfig
    {
        public string IdConfig { get; set; }
        public Nullable<int> ProximoNoPrestamo { get; set; }
        public Nullable<bool> NoPrestamoBloqueado { get; set; }
        public Nullable<int> ProximoNoOrden { get; set; }
        public Nullable<bool> NoOrdenBloqueado { get; set; }
        public Nullable<int> ProximoNoPagare { get; set; }
        public Nullable<bool> PagareBloqueado { get; set; }
        public Nullable<bool> UsarCuentasContables { get; set; }
        public string RutaArchivos { get; set; }
    }
}
