//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcOrdenPagoDed
    {
        public int NuId { get; set; }
        public int NoOrden { get; set; }
        public string IdCodDeduccion { get; set; }
        public decimal Valor { get; set; }
        public bool EsPorcent { get; set; }
        public decimal Monto { get; set; }
    
        public virtual gcOrdenPago gcOrdenPago { get; set; }
    }
}
