//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcOrdenPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gcOrdenPago()
        {
            this.gcOrdenPagoDeds = new HashSet<gcOrdenPagoDed>();
        }
    
        public int NoOrden { get; set; }
        public string IdBanco { get; set; }
        public int NoPrestamo { get; set; }
        public string IdCliente { get; set; }
        public string Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public decimal Deducciones { get; set; }
        public decimal Total { get; set; }
        public string IdUsuarioCreado { get; set; }
        public string IdUsuarioProceso { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string cStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcOrdenPagoDed> gcOrdenPagoDeds { get; set; }
        public virtual gcPrestamo gcPrestamo { get; set; }
    }
}
