//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcPrestamosAmor
    {
        public int NuId { get; set; }
        public Nullable<int> NoPrestamo { get; set; }
        public Nullable<int> NoCuota { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Capital { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> TotalPago { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual gcPrestamo gcPrestamo { get; set; }
    }
}
