//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icAlmacene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icAlmacene()
        {
            this.arFacturas = new HashSet<arFactura>();
            this.icAjustes = new HashSet<icAjuste>();
            this.icBines = new HashSet<icBine>();
            this.icInventarioFisicoes = new HashSet<icInventarioFisico>();
            this.icProductosInventarios = new HashSet<icProductosInventario>();
            this.icRecepciones = new HashSet<icRecepcione>();
            this.icRequisicionesSalidas = new HashSet<icRequisicionesSalida>();
            this.icRequisicionesTransfs = new HashSet<icRequisicionesTransf>();
            this.icRequisicionesTransfs1 = new HashSet<icRequisicionesTransf>();
            this.posTurnos = new HashSet<posTurno>();
        }
    
        public string IdAlmacen { get; set; }
        public string Descripcion { get; set; }
        public string Telefono { get; set; }
        public string IdCuenta { get; set; }
        public bool ControlaLote { get; set; }
        public bool Facturar { get; set; }
        public bool FacturarNegativo { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFactura> arFacturas { get; set; }
        public virtual glCuenta glCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icAjuste> icAjustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icBine> icBines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icInventarioFisico> icInventarioFisicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductosInventario> icProductosInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcione> icRecepciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesSalida> icRequisicionesSalidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransf> icRequisicionesTransfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransf> icRequisicionesTransfs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posTurno> posTurnos { get; set; }
    }
}
