//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icBine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icBine()
        {
            this.icInventarioFisicoDetalles = new HashSet<icInventarioFisicoDetalle>();
            this.icProductosInventarios = new HashSet<icProductosInventario>();
            this.icRecepcionesDetalles = new HashSet<icRecepcionesDetalle>();
            this.icRequisicionesSalidaDetalles = new HashSet<icRequisicionesSalidaDetalle>();
            this.icRequisicionesTransfDetalles = new HashSet<icRequisicionesTransfDetalle>();
            this.icRequisicionesTransfDetalles1 = new HashSet<icRequisicionesTransfDetalle>();
        }
    
        public string IdBin { get; set; }
        public string IdAlmacen { get; set; }
        public string Descripcion { get; set; }
        public bool lStatus { get; set; }
    
        public virtual icAlmacene icAlmacene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icInventarioFisicoDetalle> icInventarioFisicoDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductosInventario> icProductosInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcionesDetalle> icRecepcionesDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesSalidaDetalle> icRequisicionesSalidaDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransfDetalle> icRequisicionesTransfDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransfDetalle> icRequisicionesTransfDetalles1 { get; set; }
    }
}
