//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icDepto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icDepto()
        {
            this.arFacturasDetalles = new HashSet<arFacturasDetalle>();
            this.glCuentas = new HashSet<glCuenta>();
            this.icRequisicionesSalidas = new HashSet<icRequisicionesSalida>();
            this.icTipoInventarioCtasCostos = new HashSet<icTipoInventarioCtasCosto>();
            this.icTipoInventarioCtasIngresos = new HashSet<icTipoInventarioCtasIngreso>();
            this.glCuentas1 = new HashSet<glCuenta>();
            this.glCuentas2 = new HashSet<glCuenta>();
        }
    
        public string IdDepto { get; set; }
        public string Descripcion { get; set; }
        public string Telefono { get; set; }
        public bool CentroIngreso { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDetalle> arFacturasDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<glCuenta> glCuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesSalida> icRequisicionesSalidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icTipoInventarioCtasCosto> icTipoInventarioCtasCostos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icTipoInventarioCtasIngreso> icTipoInventarioCtasIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<glCuenta> glCuentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<glCuenta> glCuentas2 { get; set; }
    }
}
