//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icInventarioFisico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icInventarioFisico()
        {
            this.icInventarioFisicoDetalles = new HashSet<icInventarioFisicoDetalle>();
        }
    
        public int NoInventario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string IdAlmacen { get; set; }
        public string Referencia { get; set; }
        public string Notas { get; set; }
        public Nullable<decimal> TotalCantidad { get; set; }
        public Nullable<decimal> TotalConteo { get; set; }
        public Nullable<decimal> TotalDiferencia { get; set; }
        public string IdUsuarioCreado { get; set; }
        public string IdUsuarioProcesado { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
        public string cStatus { get; set; }
    
        public virtual icAlmacene icAlmacene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icInventarioFisicoDetalle> icInventarioFisicoDetalles { get; set; }
    }
}
