//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icInventarioFisicoDetalle
    {
        public int NuId { get; set; }
        public int NoInventario { get; set; }
        public string IdBin { get; set; }
        public string IdProducto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Conteo { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public Nullable<decimal> TotalCantidad { get; set; }
        public Nullable<decimal> TotalConteo { get; set; }
        public Nullable<decimal> TotalDiferencia { get; set; }
    
        public virtual icBine icBine { get; set; }
        public virtual icInventarioFisico icInventarioFisico { get; set; }
        public virtual icProducto icProducto { get; set; }
    }
}
