//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icProducto()
        {
            this.icAjustesDetalles = new HashSet<icAjustesDetalle>();
            this.icInventarioFisicoDetalles = new HashSet<icInventarioFisicoDetalle>();
            this.icRecepcionesDetalles = new HashSet<icRecepcionesDetalle>();
            this.icRequisicionesSalidaDetalles = new HashSet<icRequisicionesSalidaDetalle>();
            this.icRequisicionesTransfDetalles = new HashSet<icRequisicionesTransfDetalle>();
            this.icProductosInventarios = new HashSet<icProductosInventario>();
            this.icProductosEspMiscelaneos = new HashSet<icProductosEspMiscelaneo>();
        }
    
        public string IdProducto { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public string IdTipoInventario { get; set; }
        public string IdClasificacion { get; set; }
        public string IdGrupo { get; set; }
        public string IdLinea { get; set; }
        public string IdPresentacion { get; set; }
        public string IdUnidadMedida { get; set; }
        public string IdFabricante { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string NoDeParte { get; set; }
        public string Genero { get; set; }
        public string Referencia { get; set; }
        public string CodigoBarra { get; set; }
        public byte[] Foto { get; set; }
        public string FotoModeView { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public bool Tax { get; set; }
        public string IdTax { get; set; }
        public bool EditarPrecio { get; set; }
        public bool FijarPrecio { get; set; }
        public bool Controlado { get; set; }
        public bool ControlaInventario { get; set; }
        public bool ControlaLote { get; set; }
        public Nullable<decimal> StockMinimo { get; set; }
        public Nullable<decimal> StockMaximo { get; set; }
        public Nullable<decimal> MinimoOrdenar { get; set; }
        public decimal Costo { get; set; }
        public decimal Precio { get; set; }
        public decimal Impuesto { get; set; }
        public decimal PrecioConImpuesto { get; set; }
        public decimal Utilidad { get; set; }
        public decimal UtilidadPorcent { get; set; }
        public bool Descuento { get; set; }
        public decimal DesPorcentMax { get; set; }
        public decimal DesMontoMax { get; set; }
        public string Notas { get; set; }
        public bool Activo { get; set; }
        public decimal Precio1 { get; set; }
        public decimal Utilidad1 { get; set; }
        public decimal UtilidadPorcent1 { get; set; }
        public decimal Precio2 { get; set; }
        public decimal Utilidad2 { get; set; }
        public decimal UtilidadPorcent2 { get; set; }
        public decimal Precio3 { get; set; }
        public decimal Utilidad3 { get; set; }
        public decimal UtilidadPorcent3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icAjustesDetalle> icAjustesDetalles { get; set; }
        public virtual icClasificacion icClasificacion { get; set; }
        public virtual icFabricante icFabricante { get; set; }
        public virtual icGrupo icGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icInventarioFisicoDetalle> icInventarioFisicoDetalles { get; set; }
        public virtual icLinea icLinea { get; set; }
        public virtual icPresentacion icPresentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcionesDetalle> icRecepcionesDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesSalidaDetalle> icRequisicionesSalidaDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransfDetalle> icRequisicionesTransfDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductosInventario> icProductosInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductosEspMiscelaneo> icProductosEspMiscelaneos { get; set; }
        public virtual icTipoInventario icTipoInventario { get; set; }
        public virtual icUnidadMedida icUnidadMedida { get; set; }
        public virtual SysTax SysTax { get; set; }
    }
}
