//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icProductosInventario
    {
        public int NuId { get; set; }
        public string IdProducto { get; set; }
        public string IdAlmacen { get; set; }
        public string IdBin { get; set; }
        public decimal Cantidad { get; set; }
        public bool Congelado { get; set; }
    
        public virtual icAlmacene icAlmacene { get; set; }
        public virtual icBine icBine { get; set; }
        public virtual icProducto icProducto { get; set; }
    }
}
