//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icRecepcione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icRecepcione()
        {
            this.icRecepcionesDetalles = new HashSet<icRecepcionesDetalle>();
        }
    
        public int NoRecepcion { get; set; }
        public string IdAlmacen { get; set; }
        public string IdProveedor { get; set; }
        public string IdMoneda { get; set; }
        public decimal FactorCambio { get; set; }
        public string IdFormaPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string TipoDocumento { get; set; }
        public string NoDocumento { get; set; }
        public string CAI { get; set; }
        public string NoOrdenCompra { get; set; }
        public bool DescuentoGlobalPor { get; set; }
        public decimal DescuentoGlobal { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Descuentos { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public decimal Shipping { get; set; }
        public decimal OtrosMontos { get; set; }
        public decimal TotalGeneral { get; set; }
        public decimal TotalMonedaOriginal { get; set; }
        public string Notas { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string IdUsuarioCreado { get; set; }
        public string IdUsuarioProcesado { get; set; }
        public string cStatus { get; set; }
    
        public virtual apFormaPago apFormaPago { get; set; }
        public virtual apProveedore apProveedore { get; set; }
        public virtual bnMoneda bnMoneda { get; set; }
        public virtual icAlmacene icAlmacene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcionesDetalle> icRecepcionesDetalles { get; set; }
    }
}
