//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icRequisicionesTransfDetalle
    {
        public int NuId { get; set; }
        public int NoReqTransf { get; set; }
        public string IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> TotalCosto { get; set; }
        public string IdBinOrigen { get; set; }
        public string IdBinDestino { get; set; }
        public decimal ExistenciaAnterior { get; set; }
    
        public virtual icBine icBine { get; set; }
        public virtual icBine icBine1 { get; set; }
        public virtual icProducto icProducto { get; set; }
        public virtual icRequisicionesTransf icRequisicionesTransf { get; set; }
    }
}
