//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icRecepcionesDetalle
    {
        public int NuId { get; set; }
        public int NoRecepcion { get; set; }
        public string IdBin { get; set; }
        public string IdProducto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Bonificacion { get; set; }
        public decimal Costo { get; set; }
        public decimal SubTotal { get; set; }
        public bool DescuentoEsPorcent { get; set; }
        public Nullable<decimal> DescuentoValor { get; set; }
        public Nullable<decimal> DescuentoMonto { get; set; }
        public string IdTax { get; set; }
        public Nullable<decimal> TaxValor { get; set; }
        public Nullable<decimal> TaxMonto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> OtrosMontos { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> CostoAnterior { get; set; }
        public Nullable<decimal> ExitenciaAnterior { get; set; }
        public Nullable<decimal> TotalAnterior { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> PrecioAnterior { get; set; }
        public Nullable<decimal> UtilidadPorcent { get; set; }
        public Nullable<decimal> Utilidad { get; set; }
        public Nullable<decimal> PrecioCalculado { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> PrecioConImpuesto { get; set; }
    
        public virtual icBine icBine { get; set; }
        public virtual icProducto icProducto { get; set; }
        public virtual icRecepcione icRecepcione { get; set; }
        public virtual SysTax SysTax { get; set; }
    }
}
