//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icTipoInventarioCtasCosto
    {
        public string IdTipoInventario { get; set; }
        public string IdDepto { get; set; }
        public string IdCuenta { get; set; }
    
        public virtual glCuenta glCuenta { get; set; }
        public virtual icDepto icDepto { get; set; }
        public virtual icTipoInventario icTipoInventario { get; set; }
    }
}
