//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class posCategoriasProducto
    {
        public int NuId { get; set; }
        public string IdCategoria { get; set; }
        public string IdProducto { get; set; }
        public string LabelBoton { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public Nullable<int> NoBoton { get; set; }
        public bool lStatus { get; set; }
    
        public virtual posCategoria posCategoria { get; set; }
    }
}
