//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class posConfig
    {
        public string IdConfig { get; set; }
        public string IdCliente { get; set; }
        public string IdVendedor { get; set; }
        public bool PrecioConImpuesto { get; set; }
        public bool ShowImagenProducto { get; set; }
        public bool PrintTicketMx { get; set; }
        public int FacturaPrintCopias { get; set; }
    }
}
