//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class posVendedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posVendedore()
        {
            this.arFacturas = new HashSet<arFactura>();
        }
    
        public string IdVendedor { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<decimal> TechoMinimo { get; set; }
        public string Notas { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFactura> arFacturas { get; set; }
    }
}
