//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCompania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysCompania()
        {
            this.SysFormAccesos = new HashSet<SysFormAcceso>();
            this.SysProcesosAccesos = new HashSet<SysProcesosAcceso>();
        }
    
        public int IdCompania { get; set; }
        public string Compania { get; set; }
        public string Slogan { get; set; }
        public string RazonSocial { get; set; }
        public string NumeroRTN { get; set; }
        public string IdMoneda { get; set; }
        public string ClaveActivacion { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string EmailEnFactura { get; set; }
        public string Web { get; set; }
        public byte[] Logo { get; set; }
        public string Skin { get; set; }
        public string ColorReporte { get; set; }
        public string cNameServer { get; set; }
        public string cDataBase { get; set; }
        public string cIdUser { get; set; }
        public string cPassword { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public Nullable<bool> lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysFormAcceso> SysFormAccesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysProcesosAcceso> SysProcesosAccesos { get; set; }
    }
}
