//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysCAI()
        {
            this.SysCAITerminales = new HashSet<SysCAITerminale>();
        }
    
        public int IdCAI { get; set; }
        public string CAI { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaLimiteEmision { get; set; }
        public string NoDocumentoInicial { get; set; }
        public string NoDocumentoFinal { get; set; }
        public string DocumentoFiscal { get; set; }
        public Nullable<int> NumFolios { get; set; }
        public Nullable<int> NumInicial { get; set; }
        public Nullable<int> NumFinal { get; set; }
        public Nullable<int> ProximoNumero { get; set; }
        public Nullable<bool> NumeroBloqueado { get; set; }
        public Nullable<bool> lStatus { get; set; }
        public Nullable<bool> ProximoCAI { get; set; }
        public string Notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysCAITerminale> SysCAITerminales { get; set; }
    }
}
