//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCAITerminale
    {
        public int NuId { get; set; }
        public int IdCAI { get; set; }
        public string IdSucursal { get; set; }
        public string IdTerminal { get; set; }
    
        public virtual SysCAI SysCAI { get; set; }
    }
}
