//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysProcesosAcceso
    {
        public int Id { get; set; }
        public Nullable<int> IdCompania { get; set; }
        public string IdGrupoUsuario { get; set; }
        public string IdModulo { get; set; }
        public string IdForm { get; set; }
        public string IdProceso { get; set; }
        public Nullable<bool> Acceso { get; set; }
    
        public virtual SysCompania SysCompania { get; set; }
        public virtual SysForm SysForm { get; set; }
        public virtual SysProceso SysProceso { get; set; }
        public virtual SysUsuariosGrupos SysUsuariosGrupos { get; set; }
    }
}
