//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRutaProcesosDet
    {
        public int NuId { get; set; }
        public string IdRuta { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Nivel { get; set; }
        public string Tipo { get; set; }
        public string cStatus { get; set; }
    
        public virtual SysRutaProceso SysRutaProceso { get; set; }
    }
}
