//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRutaProcesosWF
    {
        public int NuId { get; set; }
        public string IdRuta { get; set; }
        public Nullable<int> NoDocumento { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Accion { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
    }
}
