//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysTax()
        {
            this.arFacturasDetalles = new HashSet<arFacturasDetalle>();
            this.arServicios = new HashSet<arServicio>();
            this.icProductos = new HashSet<icProducto>();
            this.icRecepcionesDetalles = new HashSet<icRecepcionesDetalle>();
        }
    
        public string IdTax { get; set; }
        public string Descripcion { get; set; }
        public decimal Valor { get; set; }
        public string IdCuentaAR { get; set; }
        public string IdCuentaAP { get; set; }
        public bool ImprimirEnFactura { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDetalle> arFacturasDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arServicio> arServicios { get; set; }
        public virtual glCuenta glCuenta { get; set; }
        public virtual glCuenta glCuenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProducto> icProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcionesDetalle> icRecepcionesDetalles { get; set; }
    }
}
