//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTerminale
    {
        public string IdTerminal { get; set; }
        public string IdSucursal { get; set; }
        public string Descripcion { get; set; }
        public string TipoTerminal { get; set; }
        public string IpAddress { get; set; }
        public string HostName { get; set; }
        public bool lStatus { get; set; }
        public Nullable<bool> TipoDoc01 { get; set; }
        public Nullable<bool> TipoDoc05 { get; set; }
        public Nullable<bool> TipoDoc06 { get; set; }
        public Nullable<bool> TipoDoc07 { get; set; }
        public Nullable<bool> TipoDoc08 { get; set; }
        public Nullable<bool> TipoDoc09 { get; set; }
        public Nullable<bool> TipoDoc11 { get; set; }
    
        public virtual SysSucursale SysSucursale { get; set; }
    }
}
