//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTiposDocumento
    {
        public string IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public string IdModulo { get; set; }
        public Nullable<bool> TodosModulos { get; set; }
        public bool lStatus { get; set; }
    }
}
