//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUsuario
    {
        public string IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Clave { get; set; }
        public string IdGrupoUsuario { get; set; }
        public Nullable<int> IdCompania { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Notas { get; set; }
        public string Skin { get; set; }
        public string TiempoVisibleInicio { get; set; }
        public string TiempoVisibleFinal { get; set; }
        public string TiempoTrabajoInicio { get; set; }
        public string TiempoTrabajoFinal { get; set; }
        public string TiempoEscala { get; set; }
        public bool UsuarioAdmin { get; set; }
        public bool UsuarioDeCaja { get; set; }
        public bool TurnoAbierto { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public bool lStatus { get; set; }
    
        public virtual SysUsuariosGrupos SysUsuariosGrupos { get; set; }
    }
}
