//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMiscelaneo
    {
        public string IdTipo { get; set; }
        public string Tipo { get; set; }
        public string IdMiscelaneo { get; set; }
        public string Valor { get; set; }
    }
}
