//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebT.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPais
    {
        public string IdPais { get; set; }
        public string Pais { get; set; }
        public string IdEstado { get; set; }
        public string Estado { get; set; }
        public string IdCiudad { get; set; }
        public string Ciudad { get; set; }
    }
}
